Xdebug - exit when fail to enable

diff --git a/7.2-alpine/entrypoint b/7.2-alpine/entrypoint
--- a/7.2-alpine/entrypoint
+++ b/7.2-alpine/entrypoint
@@ -2,7 +2,13 @@
 set -e
 
 if [ "$ENABLE_XDEBUG" == "true" ]; then
-    docker-php-ext-enable xdebug
+    docker-php-ext-enable xdebug >> /dev/null 2>&1
+
+    if [ $? != "0" ]; then
+        echo "[ERROR] An error happened enabling xdebug"
+
+        exit 1
+    fi
 fi
 
 # Run as current user
